added search

diff --git a/args2array b/args2array
--- a/args2array
+++ b/args2array
@@ -1,11 +1,6 @@
 #!/bin/bash
 
 validate_option() {
-	# returns 0 if option is valid and requires arguments
-	# returns 1 if option is valid and does not require an argument
-	# returns 2 if option is invalid
-
-	# UPDATE SHOULD -
 	# return 0 if option is valid and requires 1 or more arguments
 	# return 1 if option is valid and requires exactly 1 argument
 	# return 2 if option is valid and requires 0 arguments
@@ -38,10 +33,10 @@ validate_option() {
 		local firstchar="${optstr:0:1}"
 		local offsetadjust=0
 	
-		[[ "$firstchar" != "," ]] && optstr=",$optstr" && ((offsetadjust++))
+		[[ "$firstchar" != "," ]] && optstr=",$optstr"
 		[[ "$lastchar" != "," ]] && optstr="${optstr},"
 	
-		local fullstring_matches=(",${opt}," ",${opt}:," ",${opt}!,")
+		declare -a fullstring_matches=(",${opt}," ",${opt}:," ",${opt}!,")
 		
 		local match
 		for match in "${fullstring_matches[@]}"	; do
@@ -50,8 +45,6 @@ validate_option() {
 	
 			if [[ $goffset -lt ${#optstr} ]]; then
 				# a match was found
-				((goffset++))
-				[[ "$firstchar" != "," ]] && ((goffset--))
 				if [[ "${match: -2:1}" == ":" ]]; then
 					# the option requires one or more arguments
 					return 0
@@ -62,8 +55,6 @@ validate_option() {
 					# the option does not require any arguments
 					return 2
 				fi
-			else
-				goffset=$(( ${#optstr} - offsetadjust ))			
 			fi
 		done
 	fi
@@ -78,46 +69,47 @@ args2array() {
 	while (( $# > 0 )); do	
 #		echo "first positional is '$1'"
 		if [[ ${1:0:1} == "-" ]]; then
-			__opt=${1//-/}
 			# we're working with an option
-#			echo "searching optstrings for '${__opt}'"
-			validate_option "${__opt}"
+			__opt=${1//-/}
+			if [[ ${#__opt} -gt 1 ]]; then
+				__opt=${1#'--'}
+			else
+				__opt=${1#'-'}
+			fi
+#			echo "searching optstrings for '$__opt'"
+			validate_option "$__opt"
 			__exitcode=$?
 			if [[ $__exitcode -gt 2 ]]; then
 				echo "error: option '$1' is not a valid option"
 				exit $__exitcode
 			else
-#				echo "hyphen-stripped param is: '${__opt}' and __arr[${__opt}] is '${__arr[${__opt}]}'"
+#				echo "hyphen-stripped param is: '$__opt' and __arr[$__opt] is '${__arr[$__opt]}'"
 				if [[ $__exitcode -eq 0 ]]; then
 					__ctr=0
 					for __i in "${@:2}"; do
 						if [[ ${__i:0:1} == "-" ]]; then
 							break
 						else
-							if [[ ! ${__arr[${__opt}]+isset} ]]; then
-								__arr[${__opt}]="${__i}"
+							if [[ ! ${__arr[$__opt]+isset} ]]; then
+								__arr[$__opt]="${__i}"
 							else
-								__arr[${__opt}]="${__arr[${__opt}]};${__i}"
+								__arr[$__opt]="${__arr[$__opt]};${__i}"
 							fi
-							# printf '%q\n' "${__arr[${__opt}]}"
-#							echo "appending: '${__arr[${__opt}]}'$__i' ' to __arr[${__opt}]"
-							# __arr[${__opt}]="${__arr[${__opt}]}'$__i' " # this formatting requires eval - bad
+#							echo "appending: '${__arr[$__opt]}'$__i' ' to __arr[$__opt]"
+							# __arr[$__opt]="${__arr[$__opt]}'$__i' " # this formatting requires eval - bad
 							(( __ctr++ ))
-#							echo "__arr[${__opt}] is now '${__arr[${__opt}]}'"
+#							echo "__arr[$__opt] is now '${__arr[$__opt]}'"
 						fi
 					done
 					if [[ $__ctr -eq 0 ]]; then
 						echo "error: option '$1' requires an argument"
 						exit 1
-					else
-#						echo "__ctr is '$__ctr'"
-						shift $__ctr
 					fi
 				elif [[ $__exitcode -eq 1 ]]; then
-					if [[ ! ${__arr[${__opt}]+isset} && -n "$2" && ${2:0:1} != "-" ]]; then
+					if [[ ! ${__arr[$__opt]+isset} && -n "$2" && ${2:0:1} != "-" ]]; then
 						if  [[ -z "$3" || "${3:0:1}" == "-" ]]; then
 							 __arr[$__opt]="$2"
-	                        shift
+	                        __ctr=1
 						else
 							echo "error: option '$1' takes exactly one argument"
 							exit 5
@@ -127,15 +119,22 @@ args2array() {
 						exit 5
 					fi
 				else
-					 __arr[${__opt}]=""
+					if [[ -n "$2" && ${2:0:1} != "-" ]]; then
+						echo "error: option '$1' does not take  any argument"
+						exit 5
+					else
+						__arr[$__opt]=""
+						__ctr=0
+					fi
 				fi
-				shift	
+				# all 3 blocks require a shift because each corresponds to a valid option which should be removed
+				shift $(( __ctr + 1 ))
 			fi
 		else
 			shift # ignore every option not starting with -
+				  # can maybe (but not likely) be changed in the future for some sort of positional arguments...
 		fi
 	done
-	# printf '%q\n' "${__arr[a]}"
 }
 
 unpack_args() {
@@ -146,6 +145,8 @@ unpack_args() {
 }
 
 # UNCOMMENT these lines and run the examples below for usage
+# OUTPUT, RETURN CODES, CORE FUNCTIONS HAVE ALL CHANGED SINCE
+# THESE EXAMPLES WERE COPIED, IT WILL PROBABLY CHANGE AGAIN...
 # ---------------------------------------------------------------------
 
 # SMOL_OPTS="a:b!c"    # NOT comma separated, : denotes mandatory argument
