code cleanup

diff --git a/backUP b/backUP
--- a/backUP
+++ b/backUP
@@ -97,19 +97,19 @@ parse_config() {
 	done < "$CONFIGURATION_FILE"
 
 	if [[ "${config[LOGSTOUT]}" == "true" || "${config[LOGSTOUT]}" == "1"  ]]; then
-        export __LOG_STOUT__=1
-    fi
-    if [[ -n "${config[LOGLEVEL]}" ]]; then
-        if [[ "${verb[${config[LOGLEVEL]}]+1}" ]]; then
-            export __LOG_LEVEL__=${verb[${config[LOGLEVEL]}]}
-        else
-            ewarn "$FILENAME does not recognize configuration option LOGLEVEL = ${config[LOGLEVEL]}"
-        fi
-    fi
+		export __LOG_STOUT__=1
+	fi
+	if [[ -n "${config[LOGLEVEL]}" ]]; then
+		if [[ "${verb[${config[LOGLEVEL]}]+1}" ]]; then
+			export __LOG_LEVEL__=${verb[${config[LOGLEVEL]}]}
+		else
+			ewarn "$FILENAME does not recognize configuration option LOGLEVEL = ${config[LOGLEVEL]}"
+		fi
+	fi
 	if [[ -n "${config[LOGPATH]}" ]]; then
-        export __LOGPATH__="${config[LOGPATH]}"
-        __open_logfile__
-    fi
+		export __LOGPATH__="${config[LOGPATH]}"
+		__open_logfile__
+	fi
 
 	export BORG_PASSPHRASE="${config[BORG_PASSPHRASE]}"
 	export BORG_REPO="${config[BORG_REPO]}"
@@ -124,6 +124,7 @@ parse_config() {
 }
 
 append_to_backup_list() {
+	local argument
 	for argument in "$@"; do 
 		if [[ ! -f "$argument" && ! -d "$argument" ]]; then
 			ecrit "Path '$argument' doesn't seem to exist. Exiting."
@@ -132,10 +133,10 @@ append_to_backup_list() {
 	done
 	for argument in "$@"; do
 		# normalize the input
-		file=$(readlink -e "$argument")
-		if ! grep -Fxq "$file" $BACKUP_DB; then
+		file="$(readlink -e "$argument")"
+		if ! grep -Fxq "$file" "$BACKUP_DB"; then
 			eprint "Appending '$file' to '$BACKUP_DB'"
-			echo "$file" >> $BACKUP_DB
+			echo "$file" >> "$BACKUP_DB"
 		else
 			ewarn "Entry for '$file' already exists in '$BACKUP_DB'"
 		fi
@@ -144,21 +145,21 @@ append_to_backup_list() {
 }
 
 remove_from_backup_list() {
-	num_lines=$(wc -l $BACKUP_DB | awk '{print $1}')
-	
-	typeset -A lines_passed
+	local -i db_entry_line_num num_lines=$(wc -l "$BACKUP_DB" | awk '{print $1}')
+	local -A lines_passed
+	local argument db_entry
 
 	for argument in "$@"; do
 		if [[ $argument =~ $IS_NUM_REGEX && $argument -le $num_lines ]]; then
 			# function received a number less than or equal to the number of borg backups
-			db_entry=$(sed -n "$argument{p;q}" $BACKUP_DB)
-			db_entry_line_num=$argument
+			db_entry=$(sed -n "$argument{p;q}" "$BACKUP_DB")
+			db_entry_line_num="$argument"
 		else
-			file=$(readlink -e "$argument")
-			if grep -Fxq "$file" $BACKUP_DB; then
+			file="$(readlink -e "$argument")"
+			if grep -Fxq "$file" "$BACKUP_DB"; then
 			# function received an entry tracked by the database
-				db_entry=$file
-				db_entry_line_num=$(grep -nFx "$file" $BACKUP_DB | cut -f1 -d:)
+				db_entry="$file"
+				db_entry_line_num="$(grep -nFx "$file" "$BACKUP_DB" | cut -f1 -d:)"
 			else
 				# function does not recognize the argument received
 				ecrit  "No match to '$file' found in '$BACKUP_DB'"
@@ -168,19 +169,20 @@ remove_from_backup_list() {
 		lines_passed["$db_entry_line_num"]="$db_entry"
 	done
 	
-	sed_string=""
+	local sed_string=""
 	for key in "${!lines_passed[@]}"; do
 		eprint "Removing '${lines_passed[$key]}' from '$BACKUP_DB'"
 		sed_string+="${key}d;"
 	done
 	
-	sed -i "${sed_string%;}" $BACKUP_DB
+	sed -i "${sed_string%;}" "$BACKUP_DB"
 }
 
 parse_parents() {
+	local line
 	while read line; do
 		printf '%s\n' "$line"
-	done < $BACKUP_DB | \
+	done < "$BACKUP_DB" | \
 
 	# The commands below (recursively?) creates a unique entry for the full *parent* directory structure 
 	# pointing to the file/folder we want backed up,
@@ -196,7 +198,7 @@ recurse_directories() {
 			# this recursively prints all files and subdirectories of the folder we wish to backup
 			find "$line" -print
 		fi
-	done < $BACKUP_DB
+	done < "$BACKUP_DB"
 }
 
 create_borg_backup() {
@@ -209,7 +211,7 @@ create_borg_backup() {
 list_borg_backups() {
 	printf "\n%-8s%s\n" "#" "ARCHIVE NAME"
 	printf "%s%s\n" "------  ------------"
-	counter=0
+	local -i counter
 	borg list "$BORG_REPO"	2>/dev/null | \
 		while read line; do
 			((counter+=1))
@@ -225,7 +227,8 @@ list_borg_backups() {
 }
 
 restore_borg_backup() {
-	num_archives=$(borg list "$BORG_REPO" 2>/dev/null | wc -l)
+	local -i num_archives=$(borg list "$BORG_REPO" 2>/dev/null | wc -l)
+	local borg_archive
 	# Don't change permissions of /
 	if [[ ! -d "$EXTRACT_TO" ]]; then
 		install -d -m 0755 -o "$SOME_USER" -g "$SOME_USER" "$EXTRACT_TO"
@@ -239,7 +242,7 @@ restore_borg_backup() {
 	fi
 
 	eprint "Extracting '$borg_archive' to '$EXTRACT_TO'."
-	workingdir=$(pwd)
+	local workingdir=$(pwd)
 	cd "$EXTRACT_TO"
 	borg extract "$BORG_REPO::$borg_archive" 2>/dev/null
 	if [[ $? -ne 0 ]]; then
@@ -260,20 +263,20 @@ search() {
 			echo
 		done   | \
 			awk 'BEGIN { empty = 0 } {
-		 	if ($0 == "") {
-		 		if (NR - empty == 3) {
-		 			start = 0
-		 		} else {
-		 			print data
-		 		}
-		 		empty = NR
-		 		data = ""
-		 	} else {
-		 		if (start == 0) {
-		 			start = NR
-		 		}
-		 		data = data "\n" $0
-		 	}
+			if ($0 == "") {
+				if (NR - empty == 3) {
+					start = 0
+				} else {
+					print data
+				}
+				empty = NR
+				data = ""
+			} else {
+				if (start == 0) {
+					start = NR
+				}
+				data = data "\n" $0
+			}
 		 }
 		 END { print data }'
 }
@@ -289,7 +292,12 @@ duplicate_borg_repo() {
 	if validate_repo "$primary_repo"; then
 		if [[ ${#dupe_paths[@]} -gt 0 ]]; then
 			for secondary_repo in "${dupe_paths[@]}"; do
-				rsync -au --delete "$primary_repo" "$secondary_repo"  > /dev/null
+				rsync -au --delete --timeout=1 "$primary_repo" "$secondary_repo"  > /dev/null
+				if [[ $? -ne 0 ]]; then
+					ewarn "rsync encountered an error duplicating '$primary_repo' to '$secondary_repo'"
+				else
+					edebug "Successfully duplicated to '$secondary_repo'"
+				fi
 			done
 		else
 			ewarn "No duplication paths specified. '$primary_repo' will not be duplicated"
@@ -303,7 +311,7 @@ duplicate_borg_repo() {
 print_database() {
 	printf "\n%-8s%-8s%s\n" "#" "TYPE" "PATH"
 	printf "%s%s%s\n" "------  ------  ------"
-	counter=0
+	local -i counter
 		while read line; do
 			if [[ -d $line ]]; then
 				entry_type="Folder"
@@ -323,6 +331,7 @@ print_database() {
 }
 
 get_password() {
+	local first_entry second_entry
 	read -s -p "Enter Password: " first_entry
 	echo
 	read -s -p "Re-Enter Password: " second_entry
@@ -438,8 +447,8 @@ if [[ $# -eq 0 ]]; then
 fi
 
 if [[ $EUID -ne 0 ]]; then
-    ecrit "$FILENAME requires sudo privileges."
-    exit 1
+	ecrit "$FILENAME requires sudo privileges."
+	exit 1
 fi
 
 parse_config
@@ -472,8 +481,6 @@ if [[ -v ARGS[h] ]]; then
 	exit 0
 else
 	[[ -v ARGS[conf] ]] && CONFIGURATION_FILE="$CONF_ARG" && parse_config
-	# need to add some sanity checks here... so that two configs don't conflict with each other..
-
 	[[ -v ARGS[repo] ]] && validate_repo "$REPO_ARG" && export BORG_REPO="$REPO_ARG"
 	[[ -v ARGS[pass] ]] && get_password
 	[[ -v ARGS[dest] ]] && export EXTRACT_TO="${ARGS[dest]}"
diff --git a/logging b/logging
--- a/logging
+++ b/logging
@@ -16,15 +16,15 @@ _lgreen_='\033[0;92m'
 _reset_='\033[0m'
 
 function ecrit()   { __verb__=1 elog "_purple_" "FATAL" "$*" ;}
-function eerror()  { __verb__=2 elog "_red_"    "ERROR" "$*" ;}
-function ewarn()   { __verb__=2 elog "_yellow_" "WARN"  "$*" ;}
-function einfo()   { __verb__=2 elog "_white_"  "INFO"  "$*" ;}
-function edebug()  { __verb__=3 elog "_green_"  "DEBUG" "$*" ;}
-function etrace()  { __verb__=4 elog "_cyan_"   "TRACE" "$*" ;}
+function eerror()  { __verb__=2 elog "_red_"	"ERROR" "$*" ;}
+function ewarn()   { __verb__=2 elog "_yellow_" "WARN"	"$*" ;}
+function einfo()   { __verb__=2 elog "_white_"	"INFO"	"$*" ;}
+function edebug()  { __verb__=3 elog "_green_"	"DEBUG" "$*" ;}
+function etrace()  { __verb__=4 elog "_cyan_"	"TRACE" "$*" ;}
 
 ## eprint outputs irrespective of verbosity
 function eprint() { __verb__=0 elog "_lgreen_" "*" "$*" ;}
-function edumpvar() { local -a a=(); for var in "$@"; do a+=("$var = '${!var}'  "); done; etrace "${FUNCNAME[1]} :::: ${a[*]}"; }
+function edumpvar() { local -a a=(); for var in "$@"; do a+=("$var = '${!var}'	"); done; etrace "${FUNCNAME[1]} :::: ${a[*]}"; }
 
 function elog() {
 #	if ! [[ -v cccombo_breaker ]]; then
@@ -33,7 +33,7 @@ function elog() {
 #			edumpvar __LOG_OPEN__ __LOG_LEVEL__ __verb__
 #	fi
 	if [[ ${verbosity:-2} -ge ${__verb__} ]]; then
-		printf "${!1}%5s${_reset_}  %s\n" "$2" "$3" >&${__STOUTFD__}
+		printf "${!1}%5s${_reset_}	%s\n" "$2" "$3" >&${__STOUTFD__}
 	fi
 	if [[ -n ${__LOG_OPEN__} && ${__LOG_LEVEL__} -ge ${__verb__} ]]; then
 		printf "%(%Y-%m-%d %H:%M:%S)T  ${!1}%5s${_reset_}  %s\n" -1 "$2" "$3" >>"${__LOG__}"
@@ -53,14 +53,14 @@ function dlog() {
 
 function __init_messages__() {
 	exec {__STOUTFD__}>&1
-    exec {__STERRFD__}>&2
+	exec {__STERRFD__}>&2
 	while :; do
 		while getopts ':v:' opt; do
-	        if [[ ${opt} == 'v' && ${OPTARG} =~ ^[0-4]$ ]]; then
-    	        export verbosity=${OPTARG}
-        	    break 2
-	        fi
-	    done
+			if [[ ${opt} == 'v' && ${OPTARG} =~ ^[0-4]$ ]]; then
+				export verbosity=${OPTARG}
+				break 2
+			fi
+		done
 		(( OPTIND++ ))
 		[[ $OPTIND -gt $# ]] && break
 	done
@@ -79,7 +79,7 @@ function __open_logfile__() {
 			
 			exec {__LOGFD__}>>"${__LOG__}" # only used to keep the file open...
 
-			__LOG_OPEN__=1  
+			__LOG_OPEN__=1	
 			dlog "_white_" "LOGS" "SESSION OPENED"
 
 			if [[ -n ${__LOG_STOUT__} ]]; then
@@ -87,21 +87,19 @@ function __open_logfile__() {
 				install -o "$user" -g "$user" -m 700 -d "/run/${__JOB__}/$$"
 				__SO_PIPE_PATH__="/run/${__JOB__}/$$"
 				__STOUT_PIPE__="${__SO_PIPE_PATH__}/messages.pipe"
-				__FORMATED_OUTPUT_PIPE__="${__SO_PIPE_PATH__}/filter.pipe"
-				mkfifo -m 700 "${__STOUT_PIPE__}" "${__FORMATED_OUTPUT_PIPE__}"
+				mkfifo -m 700 "${__STOUT_PIPE__}" 
 				exec {__SO_PIPE_FD__}<>"${__STOUT_PIPE__}"
 
-				sed -u 's/^/   /' "${__STOUT_PIPE__}" > "${__FORMATED_OUTPUT_PIPE__}" &
+				sed -u 's/^/   /' "${__STOUT_PIPE__}" > >(tee -a "${__LOG__}" >&"${__STOUTFD__}") &
 				__SED_PID__=$!
-				tee -a "${__LOG__}" < "${__FORMATED_OUTPUT_PIPE__}" >&${__STOUTFD__} &
-				__TEE_PID__=$!
-			   	exec 1>>"${__STOUT_PIPE__}"
+				exec 1>>"${__STOUT_PIPE__}"
 				
-				edebug "${FUNCNAME[0]} inherited stout and sterr pointers from __init_messages__ on FD: '${__STOUTFD__}' and FD: '${__STERRFD__}' respectively"
+				edebug "${FUNCNAME[0]} inherited stout from __init_messages__ on FD: '${__STOUTFD__}'"
+				edebug "${FUNCNAME[0]} inherited sterr from __init_messages__ on FD: '${__STERRFD__}'"
 				edebug "Pipe initialized on FD: '${__SO_PIPE_FD__}' pointing to '${__STOUT_PIPE__}'"
-				edebug "Tee reading from '${__STOUT_PIPE__}' on PID: '${__TEE_PID__}.' Appending to: '${__LOG__}' and FD: '${__STOUTFD__}'"
-				if [[ ${__LOG_LEVEL__} -ge 3 ]]; then
-					ls -Alh /proc/$$/fd | awk '{ print $(NF-2), $(NF-1), $NF}' | tail -n +2 >"${__STOUT_PIPE__}"
+				edebug "Sed filtering FD: '${__STOUT_PIPE__}' on PID: '${__SED_PID__}.' Appending output to: '${__LOG__}' and FD: '${__STOUTFD__}'"
+				if [[ ${__LOG_LEVEL__} -ge 4 || ${verbosity} -ge 4 ]]; then
+					ls -Alh /proc/$$/fd | awk '{ print $(NF-2), $(NF-1), $NF}' | tail -n +2 > "${__STOUT_PIPE__}"
 				fi
 				edumpvar user __STOUT_PIPE__ __SO_PIPE_FD__ __TEE_PID__
 			fi
@@ -126,12 +124,12 @@ function __end_messages__() {
 	exec 1>&${__STOUTFD__}-
 	exec 2>&${__STERRFD__}-
 	if [[ -n ${__LOG_STOUT__} ]]; then
-		kill ${__TEE_PID__} ${__SED_PID__}
+		kill ${__SED_PID__} 
 		exec {__SO_PIPE_FD__}>&-
 		rm -r "${__SO_PIPE_PATH__}"
 		unset __LOG_STOUT__
 	fi
-	unset __LOG_OPEN__ __LOGS_LOADED__ __STOUTFD__ __STERRFD__ __LOG__ __LOGPATH__ __LOGFD__ __TEE_PID__ __SO_PIPE_PATH__
+	unset __LOG_OPEN__  __STOUTFD__ __STERRFD__ __LOG__ __LOGPATH__ __LOGFD__ __SED_PID__ __SO_PIPE_PATH__
 	trap - EXIT
 }
 
